steps:
  # Correr terraform init y terraform plan en pull requests desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-init'
    args: 
    - 'init'
    - '-chdir=/workspace/pepito-company-infrastructure/environments/${_ENVIRONMENT}/'
    - '-backend-config=environments/${_ENVIRONMENT}/backend.tf'
    substitutions:
      _ENVIRONMENT: dev

