steps:
  # Correr terraform init y terraform plan en pull requests desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=$COMMIT_SHA', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']
  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-init'
    args: ['init', '-backend-config=backend.tfvars', 'environments/dev']
    condition: "build.event == 'pull_request' && build.sourceBranchName == 'feature/infra' && build.targetBranchName == 'dev'"
  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-plan'
    args: ['plan', '-var-file=variables-dev.tfvars', '-out=tfplan', 'environments/dev']
    condition: "build.event == 'pull_request' && build.sourceBranchName == 'feature/infra' && build.targetBranchName == 'dev'"

  # Correr terraform apply en push a la rama dev
  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-apply'
    args: ['apply', '-auto-approve', 'tfplan']
    waitFor: ['terraform-plan']
    condition: "build.event == 'push' && build.branchName == 'dev'"
