steps:
  # Correr los comandos de terraform cuando el trigger sea un pull request desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-init'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd environments/dev/
        echo pwd
        terraform init -backend-config=environments/dev/backend-dev.tfvars 

        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
        else
          terraform workspace new dev
        fi

        terraform workspace show

        terraform plan -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$? 
        
        if [[ "${PLAN_EXIT_CODE}" -eq 0 ]]; then 
            terraform apply -auto-approve tfplan
        else
            echo "Terraform plan failed with exit code ${PLAN_EXIT_CODE}"
            exit ${PLAN_EXIT_CODE}
        fi