steps:
  # Correr terraform init y terraform plan en pull requests desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-init'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd environments/dev/
        echo pwd
        terraform init -backend-config=environments/dev/backend-dev.tfvars 

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-workspace'
    entrypoint: sh
    args:
      - '-c'
      - |
        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
        else
          terraform workspace new dev
        fi

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-plan'
    entrypoint: sh
    args: 
      - '-c'
      - |
        cd environments/dev/
        terraform workspace show
        terraform plan -var-file=variables-dev.tfvars
