steps:
  # Correr los comandos de terraform cuando el trigger sea un pull request desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-plan'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd environments/dev/
        echo pwd
        terraform init -backend-config=environments/dev/backend-dev.tfvars 

        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
        else
          terraform workspace new dev
        fi

        terraform workspace show

        terraform plan 

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-apply'
    entrypoint: sh
    args:
      - '-c'
      - |
        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
        fi

        terraform workspace show

        cd environments/dev/
        
        terraform plan 

        if [[ "$?" -eq 0 ]]; then
            terraform apply -auto-approve
        fi
