steps:
  # Correr terraform init y terraform plan en pull requests desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-init'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd environments/dev/
        echo pwd
        terraform init -backend-config=environments/dev/backend-dev.tfvars 

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-plan'
    entrypoint: sh
    args:
      - '-c'
      - |
        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
        else
          terraform workspace new dev
        fi
        terraform workspace show
        cd environments/dev/
        terraform plan 

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-apply'
    entrypoint: sh
    args:
      - '-c'
      - |
        if terraform workspace list | grep -q "dev"; then
          terraform workspace select dev
#        else
#          terraform workspace new dev
        fi
        terraform workspace show
        cd environments/dev/
#        terraform apply -auto-approve

options:
  machineType: 'N1_HIGHCPU_8'
  substitutions:
    _TF_VERSION: '1.2.2'
  env:
    - 'PROJECT_ID=pepito-dev'
  retry:
    maxNumRetries: 3
    maxRetryDuration: '1200s'
  timeout: '1600s'
  logging: 'LEGACY'
  condition: success && '$BUILD_SOURCE_BRANCH_NAME =~ ^feature/infra$'
