steps:
  # Correr terraform init y terraform plan en pull requests desde feature/infra a dev
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout'
    args: ['clone', '--depth=1', '--branch=dev', 'https://github.com/cinthyarondon/pepito-company-infrastructure.git']

  - name: 'hashicorp/terraform:1.2.2'
    id: 'terraform-init'
    entrypoint: sh
    args:
      - '-c'
      - |
          for ENV in $(echo $_ENV | tr ',' ' '); do
            terraform init -chdir=/workspace/pepito-company-infrastructure/environments/$ENV/ -backend-config=environments/$ENV/backend.tf
          done
    env: 
      - '_ENV=dev'

